### PR TITLE
Add compiled extension for Chrome

### PR DESCRIPTION
**Pull request by SeanPrashad**
The `/dist` folder contains a variation of
https://github.com/Fauntleroy/neutral-face-emoji-tools that respects
Slack's rate-limit of 20 requests a minute.

### CODE REVIEW

**Comment by SeanPrashad** [comment]
This should be what we're looking for @wlonkly! I...

1. forked and patched the neutral face emoji tool
1. built it locally (which required Node version 10.16.0 since the version of gulp is outdated)
1. copied the `/dist` folder, which contains all of the stuff required for Chrome, into this repo so all emojis + the upload tool can be cloned at once
1. Updated README with some collapsible sections to allow readers to see each option more clearly

Please give it a try and let me know what you think! I've tested a queue of 1,200+ emojis and it worked fine by uploading 20 every minute 🙌🏽

**Comment by SeanPrashad** [comment]
My fork of the neutral face emoji tool lives here: https://github.com/SeanPrashad/respectful-emoji-tool#respectful-emoji-tool

**Comment by wlonkly** [comment]
Hah, I don't have a Slack to test on, because I've uploaded all the emoji to all the Slacks I'm on that would be open to having them! This is a great approach though. Thanks for doing it!

And aha, that was the Node problem, I gave up while trying to get it to work on newer `gulp` rather than downgrading node.

**Comment by SeanPrashad** [comment]
Ok! I'm going to land this then

**Comment by wlonkly** [comment]
One thing that occurs to me: not sure how wide an audience this repo has, but `extension` might be a clearer directory name than `dist`.

**Comment by wlonkly** [comment]
Oops, I was too late :)

**Comment by SeanPrashad** [comment]
Good idea! I'll update it!

**Pull request merged**
